# Localization utility
# This file contains the configuration for the localization utility
# This program will generate the localization files for the specified locales

origin_file_extension: dart
origin_locale: es
output_locales: [en, fr, id, pt, sw, it, de, zh, ja, ko, ru, hi, nl]
output_folder: output
input_folder: /Users/noel/Documents/xilion/flutter/yimitpv
copy_mode: true